#5# List three observations of all inputs (not sample inputs) observed at the same time
# Format: (time: str, station1_input: int, station2_input: str, station3_input: int, station4_input: int, station5_input: str, station6_input: int, station7_input: str)
# Example: ('12:30:00', 1, '1990-01-01', 2, 3, "John", 4, "e=mc^2")
observation1 = ...
observation2 = ...
observation3 = ...